### testing api call

### User
#### get user
GET   http://localhost:8080/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzQGEuY29tIiwiaWF0IjoxNzM5NjEwNDc4LCJleHAiOjE3Mzk2OTY4Nzh9.wWlVC5NBkUHYujWHSFwIAi9O4xThgpSTzXFxWGXS5Ms


### Register user

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name":"idhhhh",
    "email":"aaa@gmail.com",
    "password":"aaa"
}


### Login user 
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email":"aaa@gmail.com",
    "password":"aaa"
}


### post transacrion 
POST http://localhost:8080/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NDAwNDQwNTcsImV4cCI6MTc0MDEzMDQ1N30.cQnvPBhIUdoB8J9LGkEPYVpfc7LRCi5qQLlxVFPsk_A

{
    "type":"Expense",
    "amount":200,
    "date":"12-10-2020",
    "description":"by aama"
}

### GEt 
GET  http://localhost:8080/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NDAwNDQwNTcsImV4cCI6MTc0MDEzMDQ1N30.cQnvPBhIUdoB8J9LGkEPYVpfc7LRCi5qQLlxVFPsk_A



### Delere tranas
DELETE http://localhost:8080/api/v1/transactions/67b6f72c18443b122c7ce0f8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NDAwNDQwNTcsImV4cCI6MTc0MDEzMDQ1N30.cQnvPBhIUdoB8J9LGkEPYVpfc7LRCi5qQLlxVFPsk_A


###
DELETE http://localhost:8080/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzM5Njk5Njc0LCJleHAiOjE3Mzk3ODYwNzR9.4E5F7D6mssJcfFLkcEmDx1vzdeI9PoiwCNMV-9KY1t8

{
    "transactionsid":[
        "67b19614725e63eae9901c68"
    ]
}

###
POST  http://localhost:8080/openaii
Content-Type: application/json

{
    "question":"who is trump"
}
